# Generated by Django 5.0.7 on 2024-08-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_apartment_house_delete_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='additional_equipment',
            field=models.CharField(blank=True, choices=[('garaza', 'Garaza'), ('garazno mesto', 'Garazno Mesto'), ('spoljno parking mesto', 'Spoljno Parking Mesto'), ('javni parking', 'Javni Parking'), ('vesernica', 'Vesernica'), ('igraliste', 'Igraliste'), ('lift', 'Lift')], max_length=25),
        ),
        migrations.AddField(
            model_name='apartment',
            name='aparment_type',
            field=models.CharField(blank=True, choices=[('duplex', 'Duplex'), ('stan u kuci', 'Stan U Kuci'), ('dvorisni stan', 'Dvorisni Stan'), ('penthaus', 'Penthaus'), ('salonski stan', 'Salonski Stan'), ('stan u zgradi', 'Stan U Zgradi')], max_length=25),
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor_level',
            field=models.CharField(blank=True, choices=[('suteren', 'Suteren'), ('prizemlje', 'Prizemlje'), ('visoko prizemlje', 'Visoko Prizemlje'), ('nije poslednji sprat', 'Nije Poslednji Sprat'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=25),
        ),
        migrations.AddField(
            model_name='apartment',
            name='heating_type',
            field=models.CharField(blank=True, choices=[('centralno grejanje', 'Centralno Grejanje'), ('ta pec', 'TA Pec'), ('klima uredjaj', 'Klima Uredjaj'), ('etazno grejanje na struju', 'Etazno Grejanje Na Struju'), ('etazno grejanje na cvrsto gorivo', 'Etazno Grejanje Na Cvrsto Gorivo'), ('etazno grejanje na gas', 'Etazno Grejanje Na Gas'), ('podno grejanje', 'Podno Grejanje')], max_length=32),
        ),
        migrations.AddField(
            model_name='apartment',
            name='hot_water',
            field=models.CharField(blank=True, choices=[('toplana', 'Toplana'), ('bojler', 'Bojler'), ('kotao na gas', 'Kotao Na Gas'), ('kotao na struju', 'Kotao Na Struju'), ('grejanje na cvrsto gorivo', 'Grejanje Na Cvrsto Gorivo')], max_length=25),
        ),
        migrations.AddField(
            model_name='apartment',
            name='located',
            field=models.CharField(blank=True, choices=[('centar', 'Centar'), ('vikend naselje', 'Vikend Naselje'), ('periferija', 'Periferija'), ('strogi centar grada', 'Strogi Centar Grada'), ('zaseok', 'Zaseok'), ('stambeno naselje', 'Stambeno Naselje'), ('mirna lokacija', 'Mirna Lokacija')], max_length=25),
        ),
        migrations.AddField(
            model_name='apartment',
            name='property_condition',
            field=models.CharField(blank=True, choices=[('izvorno stanje', 'Izvorno Stanje'), ('standardna gradnja', 'Standardna Gradnja'), ('novogradnja', 'Novogradnja'), ('u pripremi', 'U Pripremi'), ('u izgradnji', 'U Izgradnji'), ('zavrsena izgradnja', 'Zavrsena Izgradnja'), ('delimicna rekonstrukcija', 'Delimicna Rekonstrukcija')], max_length=25),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='listing_type',
            field=models.CharField(choices=[('iznajmljivanje', 'Iznajmljivanje'), ('prodaja', 'Prodaja')], max_length=20),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='structure',
            field=models.CharField(blank=True, choices=[('garsonjera', 'Garsonjera'), ('jednosoban stan', 'Jednosoban Stan'), ('dvosoban stan', 'Dvosoban stan'), ('trosoban stan', 'Trosoban stan'), ('cetvrosoban stan', 'Cetvorosoban stan'), ('petosoban+ stan', 'Petosoban+ stan')], max_length=23),
        ),
        migrations.AlterField(
            model_name='house',
            name='listing_type',
            field=models.CharField(choices=[('iznajmljivanje', 'Iznajmljivanje'), ('prodaja', 'Prodaja')], max_length=20),
        ),
    ]
