# Generated by Django 5.0.7 on 2024-08-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_agencie_bank_investor_delete_agencies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=models.ImageField(upload_to='banks/logos/'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='logo',
            field=models.ImageField(upload_to='investors/logos/'),
        ),
    ]
