# Generated by Django 5.0.7 on 2024-08-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_bank_logo_alter_investor_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='category',
            field=models.CharField(blank=True, choices=[('stanovi', 'Stanovi'), ('kuce', 'Kuće'), ('sobe', 'Sobe'), ('ostali tipovi prostora', 'Ostali tipovi prostora'), ('gradjevinska zemljista', 'Građevinska zemljišta'), ('poljoprivredna zemljista', 'Poljoprivredna zemljišta'), ('vikendice i brvnare', 'Vikendice i brvnare'), ('stan na dan', 'Stan na dan'), ('poslovni prostori', 'Poslovni prostori'), ('ugostiteljski objekti', 'Ugostiteljski objekti'), ('stan na dan', 'Stan na dan'), ('poslovni prostori', 'Poslovni prostori'), ('sportski objekti', 'Sportski objekti'), ('proizvodni objekti', 'Proizvodni objekti')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('garsonjera', 'Garsonjera'), ('jednosoban stan', 'Jednosoban stan'), ('dvosoban stan', 'Dvosoban stan'), ('trosoban stan', 'Trosoban stan'), ('cetvorosoban stan', 'Četvorosoban stan'), ('petosoban+ stan', 'Petosoban+ stan'), ('porodicna kuca', 'Porodična kuća'), ('kuce sa vise stanova', 'Kuće sa više stanova'), ('montazne kuce', 'Montažne kuće'), ('duplex kuce', 'Duplex kuće'), ('garaze i parking mesta', 'Garaže i parking mesta'), ('bastenska kucica / Zimovnik', 'Baštenska kućica / Zimovnik'), ('skladista/ ostave', 'Skladišta/ Ostave'), ('prostorije za hobi', 'Prostorije za hobi'), ('vocnjak', 'Voćnjak'), ('livada, pašnjak', 'Livada, pašnjak'), ('obradiva zemlja', 'Obradiva zemlja'), ('sumsko zemljište', 'Šumsko zemljište'), ('pokretna kuca / bungalov', 'Pokretna kuća / bungalov'), ('brvnara', 'Brvnara'), ('vikendica, kuca za odmor', 'Vikendica, Kuća za odmor'), ('apartmani u hotelu', 'Apartmani u hotelu'), ('apartmani u kuci', 'Apartmani u kući'), ('apartmani u stambenoj zgradi', 'Apartmani u stambenoj zgradi'), ('kancelarije', 'Kancelarije'), ('poslovna zgrada', 'Poslovna zgrada'), ('komercijalni objekat / lokal', 'Komercijalni objekat / lokal'), ('magacin', 'Magacin'), ('ordinacija', 'Ordinacija'), ('restoran', 'Restoran'), ('hotel, prenoćište', 'Hotel, prenoćište'), ('kafici', 'Kafići'), ('spa centar', 'Spa centar'), ('sportski objekat', 'Sportski objekat'), ('poljoprivredni objekti', 'Poljoprivredni objekti'), ('proizvodni prostor', 'Proizvodni prostor'), ('radionice / servisi', 'Radionice / Servisi')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='category',
            field=models.CharField(blank=True, choices=[('stanovi', 'Stanovi'), ('kuce', 'Kuće'), ('sobe', 'Sobe'), ('ostali tipovi prostora', 'Ostali tipovi prostora'), ('gradjevinska zemljista', 'Građevinska zemljišta'), ('poljoprivredna zemljista', 'Poljoprivredna zemljišta'), ('vikendice i brvnare', 'Vikendice i brvnare'), ('stan na dan', 'Stan na dan'), ('poslovni prostori', 'Poslovni prostori'), ('ugostiteljski objekti', 'Ugostiteljski objekti'), ('stan na dan', 'Stan na dan'), ('poslovni prostori', 'Poslovni prostori'), ('sportski objekti', 'Sportski objekti'), ('proizvodni objekti', 'Proizvodni objekti')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('garsonjera', 'Garsonjera'), ('jednosoban stan', 'Jednosoban stan'), ('dvosoban stan', 'Dvosoban stan'), ('trosoban stan', 'Trosoban stan'), ('cetvorosoban stan', 'Četvorosoban stan'), ('petosoban+ stan', 'Petosoban+ stan'), ('porodicna kuca', 'Porodična kuća'), ('kuce sa vise stanova', 'Kuće sa više stanova'), ('montazne kuce', 'Montažne kuće'), ('duplex kuce', 'Duplex kuće'), ('garaze i parking mesta', 'Garaže i parking mesta'), ('bastenska kucica / Zimovnik', 'Baštenska kućica / Zimovnik'), ('skladista/ ostave', 'Skladišta/ Ostave'), ('prostorije za hobi', 'Prostorije za hobi'), ('vocnjak', 'Voćnjak'), ('livada, pašnjak', 'Livada, pašnjak'), ('obradiva zemlja', 'Obradiva zemlja'), ('sumsko zemljište', 'Šumsko zemljište'), ('pokretna kuca / bungalov', 'Pokretna kuća / bungalov'), ('brvnara', 'Brvnara'), ('vikendica, kuca za odmor', 'Vikendica, Kuća za odmor'), ('apartmani u hotelu', 'Apartmani u hotelu'), ('apartmani u kuci', 'Apartmani u kući'), ('apartmani u stambenoj zgradi', 'Apartmani u stambenoj zgradi'), ('kancelarije', 'Kancelarije'), ('poslovna zgrada', 'Poslovna zgrada'), ('komercijalni objekat / lokal', 'Komercijalni objekat / lokal'), ('magacin', 'Magacin'), ('ordinacija', 'Ordinacija'), ('restoran', 'Restoran'), ('hotel, prenoćište', 'Hotel, prenoćište'), ('kafici', 'Kafići'), ('spa centar', 'Spa centar'), ('sportski objekat', 'Sportski objekat'), ('poljoprivredni objekti', 'Poljoprivredni objekti'), ('proizvodni prostor', 'Proizvodni prostor'), ('radionice / servisi', 'Radionice / Servisi')], max_length=32, null=True),
        ),
    ]
