# Generated by Django 5.0.7 on 2024-09-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_house_yard_area_alter_apartment_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_category',
            field=models.CharField(blank=True, choices=[('klasicna kuca', 'Klasična kuća'), ('porodicna vila', 'Porodična kuća'), ('bungalov', 'Bungalov'), ('drvena kuca', 'Drvena kuća '), ('viseporodicna kuca', 'Višeporodična kuća')], max_length=23),
        ),
        migrations.AddField(
            model_name='house',
            name='house_type',
            field=models.CharField(blank=True, choices=[('porodicna kuca', 'Porodična kuća'), ('kuce sa vise stanova', 'Kuće sa više stanova'), ('montazne kuce', 'Montažne kuće'), ('duplex kuca', 'Duplex kuće')], max_length=23),
        ),
        migrations.AddField(
            model_name='house',
            name='land_area_in_ares',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='sewage_system',
            field=models.CharField(blank=True, choices=[('javna kanalizacija', 'Javna kanalizacija'), ('septicka jama sa prelivnom jamom', 'Septička jama sa prelivnom jamom'), ('septicka jama bez prelivne jame', 'Septička jama bez prelivne jame'), ('bez odvodnog sistema', 'Bez odvodnog sistema')], max_length=32),
        ),
        migrations.AddField(
            model_name='house',
            name='terrain',
            field=models.CharField(blank=True, choices=[('blaga kosina', 'Blaga kosina'), ('kosina', 'Kosina'), ('ravno', 'Ravno'), ('terasasto zemljiste', 'Terasasto zemljište'), ('drugo', 'Drugo')], max_length=23),
        ),
        migrations.AddField(
            model_name='house',
            name='total_number_of_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
