# Generated by Django 5.0.7 on 2024-09-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_house_house_category_house_house_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='total_number_of_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
