# Generated by Django 5.0.7 on 2024-09-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_client_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='additional_equipment',
            field=models.CharField(blank=True, choices=[('garaza', 'Garaža'), ('garazno mesto', 'Garažno Mesto'), ('spoljno parking mesto', 'Spoljno Parking Mesto'), ('javni parking', 'Javni Parking'), ('vesernica', 'Vešernica'), ('igraliste', 'Igralište'), ('lift', 'Lift')], max_length=25),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='heating_type',
            field=models.CharField(blank=True, choices=[('centralno grejanje', 'Centralno Grejanje'), ('ta pec', 'TA Pec'), ('klima uredjaj', 'Klima Uredjaj'), ('etazno grejanje na struju', 'Etazno Grejanje Na Struju'), ('etazno grejanje na cvrsto gorivo', 'Etažno Grejanje Na Cvrsto Gorivo'), ('etazno grejanje na gas', 'Etažno Grejanje Na Gas'), ('podno grejanje', 'Podno Grejanje')], max_length=32),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='property_condition',
            field=models.CharField(blank=True, choices=[('izvorno stanje', 'Izvorno Stanje'), ('standardna gradnja', 'Standardna Gradnja'), ('novogradnja', 'Novogradnja'), ('u pripremi', 'U Pripremi'), ('u izgradnji', 'U Izgradnji'), ('zavrsena izgradnja', 'Završena Izgradnja'), ('delimicna rekonstrukcija', 'Delimicna Rekonstrukcija')], max_length=25),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(blank=True, choices=[('fizicko lice', 'Fizičko lice'), ('agencija', 'Agencija'), ('investitor', 'Investitor'), ('banka', 'Banka'), ('drugo pravno lice', 'Drugo pravno lice')], max_length=32),
        ),
    ]
