# Generated by Django 5.0.7 on 2025-10-15 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='agency',
            name='city',
            field=models.CharField(choices=[('aleksinac', 'Aleksinac'), ('alibunar', 'Alibunar'), ('arandjelovac', 'Aranđelovac'), ('asanja', 'Ašanja'), ('badanj', 'Badanj'), ('badovinci', 'Badovinci'), ('bajina_basta', 'Bajina Bašta'), ('baljevac', 'Baljevac'), ('banatski_karlovac', 'Banatski Karlovac'), ('banatski_sokolac', 'Banatski Sokolac'), ('banatsko_novo_selo', 'Banatsko Novo Selo'), ('banja_koviljaca', 'Banja Koviljača'), ('banja_vrujci', 'Banja Vrujci'), ('banjani', 'Banjani'), ('banostor', 'Banoštor'), ('baranda', 'Baranda'), ('baric', 'Barič'), ('batocina', 'Batočina'), ('bavaniste', 'Bavanište'), ('bac', 'Bač'), ('backa_palanka', 'Bačka Palanka'), ('backa_topola', 'Bačka Topola'), ('backi_gracac', 'Bački Gračac'), ('backi_jarak', 'Bački Jarak'), ('backi_petrovac', 'Bački Petrovac'), ('backo_gradiste', 'Bačko Gradište'), ('backo_petrovo_selo', 'Bačko Petrovo Selo'), ('begec', 'Begeč'), ('beograd', 'Beograd'), ('beocin', 'Beočin'), ('berkovac', 'Berkovac'), ('becej', 'Bečej'), ('becmen', 'Bečmen'), ('beska', 'Beška'), ('bogatic', 'Bogatić'), ('bojnik', 'Bojnik'), ('bolec', 'Boleč'), ('boljevac', 'Boljevac'), ('boljevci', 'Boljevci'), ('bor', 'Bor'), ('bosilegrad', 'Bosilegrad'), ('bosnjace', 'Bošnjace'), ('brajkovac', 'Brajkovac'), ('brzece', 'Brzeće'), ('bubanj', 'Bubanj'), ('bujanovac', 'Bujanovac'), ('bukovac', 'Bukovac'), ('budjanovci', 'Buđanovci'), ('carina', 'Carina'), ('crepaja', 'Crepaja'), ('crvenka', 'Crvenka'), ('cvetke', 'Cvetke'), ('deliblato', 'Deliblato'), ('despotovac', 'Despotovac'), ('dec', 'Deč'), ('divci', 'Divci'), ('divos', 'Divoš'), ('divcibare', 'Divčibare'), ('dici', 'Dići'), ('dobanovci', 'Dobanovci'), ('dobrica', 'Dobrica'), ('doljevac', 'Doljevac'), ('dolovo', 'Dolovo'), ('donja_satornja', 'Donja Šatornja'), ('donji_milanovac', 'Donji Milanovac'), ('draginje', 'Draginje'), ('drazevac', 'Draževac'), ('dubovac', 'Dubovac'), ('dudovica', 'Dudovica'), ('erdevik', 'Erdevik'), ('futog', 'Futog'), ('gadin_han', 'Gadžin Han'), ('gaj', 'Gaj'), ('gajdobra', 'Gajdobra'), ('glogonj', 'Glogonj'), ('glozan', 'Gložan'), ('golubac', 'Golubac'), ('gornji_milanovac', 'Gornji Milanovac'), ('gospodinci', 'Gospođinci'), ('gracac', 'Gračac'), ('grdica', 'Grdica'), ('grocka', 'Grocka'), ('guca_varosica', 'Guča (varošica)'), ('hrtkovci', 'Hrtkovci'), ('idvor', 'Idvor'), ('indjija', 'Inđija'), ('irig', 'Irig'), ('ivanjica', 'Ivanjica'), ('ivanovo', 'Ivanovo'), ('jabuka', 'Jabuka'), ('jabucje', 'Jabučje'), ('jagodina', 'Jagodina'), ('jajcic', 'Jajčić'), ('jakovo', 'Jakovo'), ('jarcujak', 'Jarčujak'), ('jasenak', 'Jasenak'), ('jelasnica', 'Jelašnica'), ('kanjiza', 'Kanjiža'), ('kaonik', 'Kaonik'), ('karlovcic', 'Karlovčić'), ('kac', 'Kać'), ('kacarevo', 'Kačarevo'), ('kikinda', 'Kikinda'), ('kisac', 'Kisač'), ('kladovo', 'Kladovo'), ('knic', 'Knić'), ('knjazevac', 'Knjaževac'), ('konarevo', 'Konarevo'), ('konatice', 'Konatice'), ('kopaonik', 'Kopaonik'), ('kostol', 'Kostol'), ('kovacica', 'Kovačica'), ('kovilj', 'Kovilj'), ('kovin', 'Kovin'), ('kragujevac', 'Kragujevac'), ('kraljevo', 'Kraljevo'), ('krivi_vir', 'Krivi Vir'), ('krusedol_selo', 'Krušedol Selo'), ('krusevac', 'Kruševac'), ('krusevac', 'Kruševac'), ('krcedin', 'Krčedin'), ('kula', 'Kula'), ('kupinovo', 'Kupinovo'), ('kursumlija', 'Kuršumlija'), ('lazarevac', 'Lazarevac'), ('lacarak', 'Laćarak'), ('lebane', 'Lebane'), ('ledinci', 'Ledinci'), ('leskovac', 'Leskovac'), ('lezimir', 'Ležimir'), ('lipolist', 'Lipolist'), ('lipovica', 'Lipovica'), ('ljig', 'Ljig'), ('ljubovija', 'Ljubovija'), ('loznica', 'Loznica'), ('majur', 'Majur'), ('mala_mostanica', 'Mala Moštanica'), ('mali_pozarevac', 'Mali Požarevac'), ('mali_zvornik', 'Mali Zvornik'), ('malo_crnice', 'Malo Crniće'), ('maradik', 'Maradik'), ('mataruska_banja', 'Mataruška Banja'), ('melenci', 'Melenci'), ('merosina', 'Merošina'), ('metikos', 'Metikoš'), ('metkovic', 'Metković'), ('milesevo', 'Mileševo'), ('miljkovica', 'Miljkovica'), ('mionica_selo', 'Mionica (selo)'), ('mionica_varosica', 'Mionica (varošica)'), ('mionica', 'Mionica'), ('mirasevac', 'Miraševac'), ('mislodin', 'Mislođin'), ('mladenovac_selo', 'Mladenovac (selo)'), ('mladenovac', 'Mladenovac'), ('mramor', 'Mramor'), ('mramorak', 'Mramorak'), ('mrcici', 'Mrčići'), ('nadrlje', 'Nadrlje'), ('nemenikuc', 'Nemenikuće'), ('nis', 'Niš'), ('niska_banja', 'Niška Banja'), ('nova_varos', 'Nova Varoš'), ('novi_becej', 'Novi Bečej'), ('novi_pazar', 'Novi Pazar'), ('novi_sad', 'Novi Sad'), ('novi_slankamen', 'Novi Slankamen'), ('obrenovac', 'Obrenovac'), ('obrovac', 'Obrovac'), ('odzaci', 'Odžaci'), ('omoljica', 'Omoljica'), ('oplanići', 'Oplanići'), ('opovo', 'Opovo'), ('orasac', 'Orašac'), ('ostrovo', 'Ostrovo'), ('ovcar_banja', 'Ovčar Banja'), ('ovca', 'Ovča'), ('padina', 'Padina'), ('palanka', 'Palanka'), ('palic', 'Palić'), ('palilula', 'Palilula'), ('pancevo', 'Pančevo'), ('paracin', 'Paraćin'), ('pasic', 'Pasić'), ('patizan', 'Partizan'), ('pecinci', 'Pećinci'), ('pec', 'Peć'), ('pecani', 'Pećani'), ('petka', 'Petka'), ('petkovica', 'Petkovica'), ('petrovaradin', 'Petrovaradin'), ('pinosava', 'Pinosava'), ('pirot', 'Pirot'), ('pirot', 'Pirot'), ('piscani', 'Piščani'), ('pivnica', 'Pivnica'), ('plac', 'Plac'), ('podgorica', 'Podgorica'), ('podrezak', 'Podrezak'), ('pojac', 'Pojac'), ('popovac', 'Popovac'), ('popovac', 'Popovac'), ('potpec', 'Potpeć'), ('pozega', 'Požega'), ('pozarevac', 'Požarevac'), ('prekovac', 'Prekovac'), ('presevo', 'Preševo'), ('priboj', 'Priboj'), ('pridvorica', 'Pridvorica'), ('prigrevica', 'Prigrevica'), ('prijepolje', 'Prijepolje'), ('prokuplje', 'Prokuplje'), ('raca', 'Rača'), ('racovnik', 'Racovnik'), ('rakovica', 'Rakovica'), ('rakovac', 'Rakovac'), ('ralja', 'Ralja'), ('rataje', 'Rataje'), ('ravan', 'Ravan'), ('ravnje', 'Ravnje'), ('ravanic', 'Ravanic'), ('redjina', 'Redjina'), ('renic', 'Renić'), ('rezek', 'Rezek'), ('rešica', 'Rešica'), ('riznic', 'Riznic'), ('rojkova', 'Rojkova'), ('rojkovac', 'Rojkovac'), ('rojkovići', 'Rojkovići'), ('rojkovic', 'Rojković'), ('ronic', 'Ronic'), ('roncovic', 'Roncović'), ('ronići', 'Ronići'), ('rovni', 'Rovni'), ('rudna_glava', 'Rudna Glava'), ('rudnik', 'Rudnik'), ('ruma', 'Ruma'), ('rusanj', 'Rusanj'), ('savinac', 'Savinac'), ('sekici', 'Sekići'), ('sekulići', 'Sekulići'), ('selace', 'Selače'), ('seonica', 'Seonica'), ('sikole', 'Sikole'), ('silovo', 'Silovo'), ('sivac', 'Sivac'), ('skela', 'Skela'), ('skobalj', 'Skobalj'), ('slatina', 'Slatina'), ('slepčević', 'Slepčević'), ('slijepčević', 'Slijepčević'), ('slovica', 'Slovica'), ('smederevo', 'Smederevo'), ('smederevska_palanka', 'Smederevska Palanka'), ('soko_banja', 'Soko Banja'), ('sokolac', 'Sokolac'), ('sombor', 'Sombor'), ('sopot', 'Sopot'), ('sopron', 'Sopron'), ('sovljak', 'Sovljak'), ('sracinec', 'Sračinec'), ('sremska_mitrovica', 'Sremska Mitrovica'), ('sremski_karlovci', 'Sremski Karlovci'), ('sremski_mihaljevci', 'Sremski Mihaljevci'), ('stara_pazova', 'Stara Pazova'), ('starcevo', 'Starčevo'), ('subotica', 'Subotica'), ('surcin', 'Surčin'), ('surdulica', 'Surdulica'), ('svetozarevo', 'Svetozarevo'), ('svrljig', 'Svrljig'), ('tajšić', 'Tajšić'), ('temerin', 'Temerin'), ('teskic', 'Teskić'), ('titov', 'Titov'), ('trstenik', 'Trstenik'), ('tumane', 'Tumane'), ('ulcinj', 'Ulcinj'), ('umberg', 'Umberg'), ('učiteljić', 'Učiteljić'), ('uzice', 'Užice'), ('valjevo', 'Valjevo'), ('veliki_idjos', 'Veliki Iđoš'), ('velika_plana', 'Velika Plana'), ('velika_hoča', 'Velika Hoča'), ('velika_jelica', 'Velika Jelica'), ('veliko_gradiste', 'Veliko Gradište'), ('vilovo', 'Vilovo'), ('vojka', 'Vojka'), ('vrbas', 'Vrbas'), ('vranje', 'Vranje'), ('vrbovac', 'Vrbovac'), ('vrnića', 'Vrnića'), ('vrnjacka_banja', 'Vrnjačka Banja'), ('vrnjci', 'Vrnjci'), ('vrcenovica', 'Vrćenovica'), ('vrcin', 'Vrčin'), ('vrsac', 'Vršac'), ('zajecar', 'Zaječar'), ('zaklopaca', 'Zaklopača'), ('zalug', 'Zalug'), ('zaovine', 'Zaovine'), ('zlatibor', 'Zlatibor'), ('zmajevo', 'Zmajevo'), ('zrenjanin', 'Zrenjanin'), ('zuce', 'Zuce'), ('zvecka', 'Zvečka'), ('cicevac', 'Ćićevac'), ('cuprija', 'Ćuprija'), ('cajetina', 'Čajetina'), ('cacak', 'Čačak'), ('cenej', 'Čenej'), ('centa', 'Čenta'), ('cerevic', 'Čerević'), ('cibukovac', 'Čibukovac'), ('cibutkovica', 'Čibutkovica'), ('coka', 'Čoka'), ('cortanovci', 'Čortanovci'), ('cukojevac', 'Čukojevac'), ('curug', 'Čurug'), ('djurinci', 'Đurinci'), ('sabac', 'Šabac'), ('sid', 'Šid'), ('simanovci', 'Šimanovci'), ('susnjar', 'Šušnjar'), ('zabalj', 'Žabalj'), ('zitiste', 'Žitište'), ('zica', 'Žiča')], max_length=32),
        ),
        migrations.AlterField(
            model_name='agency',
            name='country',
            field=models.CharField(choices=[('srbija', 'Srbija'), ('bosna_i_hercegovina', 'Bosna i Hercegovina'), ('bugarska', 'Bugarska'), ('crna_gora', 'Crna Gora'), ('grcka', 'Grčka'), ('hrvatska', 'Hrvatska')], max_length=32),
        ),
        migrations.AlterField(
            model_name='agency',
            name='description',
            field=models.CharField(blank=True, max_length=755),
        ),
        migrations.AlterField(
            model_name='agency',
            name='logo',
            field=models.ImageField(blank=True, upload_to='agencies/logos/'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only numeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='agency',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='category',
            field=models.CharField(choices=[('stanovi', 'Stanovi'), ('kuce', 'Kuće'), ('sobe', 'Sobe'), ('ostali tipovi prostora', 'Ostali tipovi prostora'), ('gradjevinska zemljista', 'Građevinska zemljišta'), ('poljoprivredna zemljista', 'Poljoprivredna zemljišta'), ('vikendice i brvnare', 'Vikendice i brvnare'), ('stan na dan', 'Stan na dan'), ('poslovni prostori', 'Poslovni prostori'), ('ugostiteljski objekti', 'Ugostiteljski objekti'), ('stan na dan', 'Stan na dan'), ('poslovni prostori', 'Poslovni prostori'), ('sportski objekti', 'Sportski objekti'), ('proizvodni objekti', 'Proizvodni objekti')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='sub_category',
            field=models.CharField(choices=[('garsonjera', 'Garsonjera'), ('jednosoban stan', 'Jednosoban stan'), ('dvosoban stan', 'Dvosoban stan'), ('trosoban stan', 'Trosoban stan'), ('cetvorosoban stan', 'Četvorosoban stan'), ('petosoban+ stan', 'Petosoban+ stan'), ('porodicna kuca', 'Porodična kuća'), ('kuce sa vise stanova', 'Kuće sa više stanova'), ('montazne kuce', 'Montažne kuće'), ('duplex kuce', 'Duplex kuće'), ('garaze i parking mesta', 'Garaže i parking mesta'), ('bastenska kucica / Zimovnik', 'Baštenska kućica / Zimovnik'), ('skladista / ostave', 'Skladišta/ Ostave'), ('prostorije za hobi', 'Prostorije za hobi'), ('vocnjak', 'Voćnjak'), ('livada, pašnjak', 'Livada, pašnjak'), ('obradiva zemlja', 'Obradiva zemlja'), ('sumsko zemljište', 'Šumsko zemljište'), ('pokretna kuca / bungalov', 'Pokretna kuća / bungalov'), ('brvnara', 'Brvnara'), ('vikendica, kuca za odmor', 'Vikendica, Kuća za odmor'), ('apartmani u hotelu', 'Apartmani u hotelu'), ('apartmani u kuci', 'Apartmani u kući'), ('apartmani u stambenoj zgradi', 'Apartmani u stambenoj zgradi'), ('kancelarije', 'Kancelarije'), ('poslovna zgrada', 'Poslovna zgrada'), ('komercijalni objekat / lokal', 'Komercijalni objekat / lokal'), ('magacin', 'Magacin'), ('ordinacija', 'Ordinacija'), ('restoran', 'Restoran'), ('hotel, prenoćište', 'Hotel, prenoćište'), ('kafici', 'Kafići'), ('spa centar', 'Spa centar'), ('sportski objekat', 'Sportski objekat'), ('poljoprivredni objekti', 'Poljoprivredni objekti'), ('proizvodni prostor', 'Proizvodni prostor'), ('radionice / servisi', 'Radionice / Servisi')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='business_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bank',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='bank',
            name='description',
            field=models.CharField(blank=True, max_length=755),
        ),
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=models.ImageField(blank=True, upload_to='banks/logos/'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only numeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='bank',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bank',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='category',
            field=models.CharField(choices=[('stanovi', 'Stanovi'), ('kuce', 'Kuće'), ('sobe', 'Sobe'), ('ostali tipovi prostora', 'Ostali tipovi prostora'), ('gradjevinska zemljista', 'Građevinska zemljišta'), ('poljoprivredna zemljista', 'Poljoprivredna zemljišta'), ('vikendice i brvnare', 'Vikendice i brvnare'), ('stan na dan', 'Stan na dan'), ('poslovni prostori', 'Poslovni prostori'), ('ugostiteljski objekti', 'Ugostiteljski objekti'), ('stan na dan', 'Stan na dan'), ('poslovni prostori', 'Poslovni prostori'), ('sportski objekti', 'Sportski objekti'), ('proizvodni objekti', 'Proizvodni objekti')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='sub_category',
            field=models.CharField(choices=[('garsonjera', 'Garsonjera'), ('jednosoban stan', 'Jednosoban stan'), ('dvosoban stan', 'Dvosoban stan'), ('trosoban stan', 'Trosoban stan'), ('cetvorosoban stan', 'Četvorosoban stan'), ('petosoban+ stan', 'Petosoban+ stan'), ('porodicna kuca', 'Porodična kuća'), ('kuce sa vise stanova', 'Kuće sa više stanova'), ('montazne kuce', 'Montažne kuće'), ('duplex kuce', 'Duplex kuće'), ('garaze i parking mesta', 'Garaže i parking mesta'), ('bastenska kucica / Zimovnik', 'Baštenska kućica / Zimovnik'), ('skladista / ostave', 'Skladišta/ Ostave'), ('prostorije za hobi', 'Prostorije za hobi'), ('vocnjak', 'Voćnjak'), ('livada, pašnjak', 'Livada, pašnjak'), ('obradiva zemlja', 'Obradiva zemlja'), ('sumsko zemljište', 'Šumsko zemljište'), ('pokretna kuca / bungalov', 'Pokretna kuća / bungalov'), ('brvnara', 'Brvnara'), ('vikendica, kuca za odmor', 'Vikendica, Kuća za odmor'), ('apartmani u hotelu', 'Apartmani u hotelu'), ('apartmani u kuci', 'Apartmani u kući'), ('apartmani u stambenoj zgradi', 'Apartmani u stambenoj zgradi'), ('kancelarije', 'Kancelarije'), ('poslovna zgrada', 'Poslovna zgrada'), ('komercijalni objekat / lokal', 'Komercijalni objekat / lokal'), ('magacin', 'Magacin'), ('ordinacija', 'Ordinacija'), ('restoran', 'Restoran'), ('hotel, prenoćište', 'Hotel, prenoćište'), ('kafici', 'Kafići'), ('spa centar', 'Spa centar'), ('sportski objekat', 'Sportski objekat'), ('poljoprivredni objekti', 'Poljoprivredni objekti'), ('proizvodni prostor', 'Proizvodni prostor'), ('radionice / servisi', 'Radionice / Servisi')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='investor',
            name='country',
            field=models.CharField(choices=[('srbija', 'Srbija'), ('bosna_i_hercegovina', 'Bosna i Hercegovina'), ('bugarska', 'Bugarska'), ('crna_gora', 'Crna Gora'), ('grcka', 'Grčka'), ('hrvatska', 'Hrvatska')], max_length=32),
        ),
        migrations.AlterField(
            model_name='investor',
            name='description',
            field=models.CharField(blank=True, max_length=755),
        ),
        migrations.AlterField(
            model_name='investor',
            name='logo',
            field=models.ImageField(blank=True, upload_to='investors/logos/'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', 'Only numeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='investor',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investor',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
