# Generated by Django 5.0.6 on 2025-10-18 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_agency_cell_phone_alter_agency_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.client'),
        ),
        migrations.AddField(
            model_name='house',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.client'),
        ),
    ]
