# Generated by Django 5.0.6 on 2025-10-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_apartment_client_house_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='heating',
        ),
        migrations.RemoveField(
            model_name='house',
            name='heating',
        ),
        migrations.AddField(
            model_name='house',
            name='heating_type',
            field=models.CharField(blank=True, choices=[('centralno grejanje', 'Centralno Grejanje'), ('ta pec', 'TA Pec'), ('klima uredjaj', 'Klima Uredjaj'), ('etazno grejanje na struju', 'Etazno Grejanje Na Struju'), ('etazno grejanje na cvrsto gorivo', 'Etažno Grejanje Na Cvrsto Gorivo'), ('etazno grejanje na gas', 'Etažno Grejanje Na Gas'), ('podno grejanje', 'Podno Grejanje')], max_length=32),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='variety',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='house',
            name='variety',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
