# Generated by Django 5.0.7 on 2025-10-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_remove_apartment_heating_remove_house_heating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='is_feautured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, upload_to='clients/profiles/'),
        ),
        migrations.AddField(
            model_name='house',
            name='is_feautured',
            field=models.BooleanField(default=False),
        ),
    ]
